project_id = "qreifrmlgfwxisrpbnwl"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.places-autocomplete]
verify_jwt = false

[functions.generate-matches]
verify_jwt = true

[functions.export-groups]
verify_jwt = true

[functions.export-external-groups]
verify_jwt = true

[functions.send-group-notifications]
verify_jwt = true

[functions.process-file-upload]
verify_jwt = true

[functions.generate-external-matches]
verify_jwt = true