// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geozilcnochlvldryjcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdlb3ppbGNub2NobHZsZHJ5amNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MTYwNjQsImV4cCI6MjA3MTk5MjA2NH0.f0krQbnQ8e2rW_xUEg30yao0c3PyaHMKHgQBYlNzVCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});