// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qreifrmlgfwxisrpbnwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyZWlmcm1sZ2Z3eGlzcnBibndsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDgwMjUsImV4cCI6MjA3MjU4NDAyNX0.XZae9SIbceStxf-YZPPSG_3unXo0RJilb7HPekYlZGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});